language: python
python:
  - "3.4"
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
# command to install dependencies
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy
  - sudo apt-get install r-base-dev
  - pip install rpy2
  - python setup.py install
  - pip install nose-cov
# command to run tests
script: nosetests --with-coverage --cover-package=FFOMP
after_success:
    - pip install coveralls
    - coveralls
